stages:
  - build

variables:
  VERSION: ${CI_COMMIT_REF_NAME}
  IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}

build:
  stage: build
  only:
    - tags
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --build-arg VERSION=$VERSION --pull -t $IMAGE .
    - docker push ${IMAGE}
